To enable flakes in Nix on Void Linux glibc and find the correct commit SHA for the Zoom version you want, follow these steps:

1. Enable Flakes in Nix
Edit the Nix configuration file:
You'll need to modify the Nix configuration file to enable flakes. Open /etc/nix/nix.conf with your preferred text editor (you may need to create the file if it doesn't exist):

#+begin_src bash
sudo mkdir -p /etc/nix
sudo nano /etc/nix/nix.conf
#+end_src

Add the following lines to enable flakes:

#+begin_src bash
experimental-features = nix-command flakes
#+end_src

Save and close the file.

Verify the configuration:
Run the following command to verify that flakes are enabled:

#+begin_src bash
nix flake --version
#+end_src

If flakes are enabled correctly, you should see the version of Nix along with the word "flake."

2. Find the Correct Commit SHA for Zoom 5.16.6
Search the Nixpkgs repository:
To find the commit SHA for Zoom version 5.16.6, you can use the GitHub search feature or command line tools to search the Nixpkgs repository.

Use GitHub search:

Go to the Nixpkgs GitHub repository.
Use the search bar to search for zoom in the nixpkgs repository.
Look for commits or PRs that mention version 5.16.6.
Use the command line:
You can clone the Nixpkgs repository and search for the version using Git:

#+begin_src bash
git clone https://github.com/NixOS/nixpkgs.git
cd nixpkgs
git log -S "version = \"5.16.6\"" -- ./pkgs/applications/video/zoom
#+end_src

This command will search the commit history for mentions of version 5.16.6 in the Zoom package definition.

The output will show the commits that include this version. You can then copy the commit SHA.

3. Install Zoom 5.16.6 Using Flakes
Once you have the commit SHA:

Use the flake to install Zoom:
Run the following command to install Zoom 5.16.6:

#+begin_src bash
nix run github:NixOS/nixpkgs/<commit-sha>#zoom
#+end_src

Replace <commit-sha> with the SHA you found.
This will install the specific version of Zoom you need.






